# Generated by Django 4.2 on 2023-04-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaleephotographs', '0002_category_alter_gallery_name_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
