# Generated by Django 4.2 on 2023-04-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaleephotographs', '0004_rename_category_image_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=250)),
                ('review', models.TextField()),
                ('image', models.ImageField(upload_to='reviewers')),
            ],
        ),
    ]
